CREATE DATABASE AMAZON1_DATA;

CREATE TABLE AMAZON1_SALES(
  ORDER_ID INT PRIMARY KEY,
  ORDER_DATE DATE,
  PRODUCT_ID INT,
  PRODUCT_CATEGORY VARCHAR(20),
  PRICE FLOAT,
  DISCOUNT_PERCENT INT,
  QUANTITY_SOLD INT,
  CUSTOMER_REGION VARCHAR(50),
  PAYMENT_METHOD VARCHAR(40),
  RATING FLOAT,
  review_count INT,
  discounted_price FLOAT,
  total_revenue FLOAT
);

SELECT*FROM AMAZON1_SALES;
SELECT COUNT(*)FROM AMAZON1_SALES;
SELECT *
FROM AMAZON1_SALES
WHERE PRODUCT_CATEGORY IS NULL;

SELECT ORDER_ID ,COUNT(*)
FROM AMAZON1_SALES
GROUP BY ORDER_ID
ORDER BY COUNT(*)
LIMIT 1000;


SELECT*FROM AMAZON1_SALES;

--WHICH TOP 10 PRODUCT HAVE THE HIGHTEST DISCOUNTS?

SELECT PRODUCT_CATEGORY ,PRICE , DISCOUNTED_PRICE,
       (PRICE - DISCOUNTED_PRICE)AS TOTAL_DISCOUNT_AMOUNT
FROM  AMAZON1_SALES
ORDER BY TOTAL_DISCOUNT_AMOUNT DESC
LIMIT 10;

-- HOW MANY TOTAL PRODUCTS ARE IN EACH CATEGORY AND WHAT IS THEIR AVERAGE RATING?

SELECT PRODUCT_CATEGORY,
      COUNT(PRODUCT_ID)AS TOTAL_PRODUCTS,
	  ROUND(AVG(RATING),2)AS AVERAGE_RATING
FROM  AMAZON1_SALES
GROUP BY PRODUCT_CATEGORY
ORDER BY TOTAL_PRODUCTS DESC;

--WHICH CATEGORIES HAVE THE HIGHTEST TOTAL SALES VALUE ?

SELECT PRODUCT_CATEGORY,
      SUM (DISCOUNTED_PRICE)AS TOTAL_SALES_VALUE
FROM  AMAZON1_SALES
GROUP BY PRODUCT_CATEGORY
ORDER BY TOTAL_SALES_VALUE DESC;

--IS THERE A RELATIONSHIPBETWEEN HIGH DISCOUNT AND PRODUCT RATINGS?

SELECT 
    CASE 
       WHEN DISCOUNT_PERCENT >= 30 THEN 'VERY HIGH DISCOUNT(30%+)'
	    WHEN DISCOUNT_PERCENT >= 15 AND DISCOUNT_PERCENT <30 THEN 'HIGH DISCOUNT(15-30%+)'
		ELSE 'MODERATE/LOW DISCOUNT(0-15%)'
	END AS DISCOUNT_RANGE,
	ROUND(AVG(PRODUCT_ID),2)AS AVG_RATING,
	COUNT(PRODUCT_ID)AS TOTAL_PRODUCTS
	FROM AMAZON1_SALES
   GROUP BY 1
   ORDER BY 1;

--WHICH ARE THE BEST- SELLING PRODUCTS WITH HIGH RATING AND MANY REVIEWS?

SELECT PRODUCT_CATEGORY,RATING,REVIEW_COUNT
FROM AMAZON1_SALES
WHERE RATING >= 4.5
  AND REVIEW_COUNT IS NOT NULL
 ORDER BY REVIEW_COUNT DESC
 LIMIT 10;

 SELECT DISTINCT ON (PRODUCT_CATEGORY)
          PRODUCT_CATEGORY,
		  RATING,
		  REVIEW_COUNT
  FROM AMAZON_SALES
  WHERE RATING >= 4.5
  AND REVIEW_COUNT IS NOT NULL
  ORDER BY PRODUCT_CATEGORY,REVIEW_COUNT DESC;